### ISSUE TITLE
Coding Language from Italian to English

### ISSUE THREAD

**Issue by NandanSatheesh** [PaolaSmakaj/PizzaASAP#1]
An Amazing Project but it would be nice to see a few things in English as well.

**Comment by NandanSatheesh** [comment]
Check out this repository for the same. 
https://github.com/NandanSatheesh/Web-Project-Pizza-Store

**Comment by PaolaSmakaj** [comment]
This work was created for my web technologies course so, obviously, it is in Italian since I live and I study here in Italy.
